### PR TITLE
fix: Zone Update

### PR DESCRIPTION
**Pull request by jbe-dw**
Hello again,

A last PR to be able to update more fields with the zone update

### CODE REVIEW

**Comment by jbe-dw** [comment]
Hello,

Thank you for taking a look at this one either.

Regars
Jerome

**Comment by jbe-dw** [comment]
up

**Comment by jbe-dw** [comment]
@mbag if you consider adding this one i'll do some changes since it will conflict with #74

**Comment by mbag** [comment]
@jbe-dw  yes, please do make changes to be compliant with #74  I already merged the 74. Thank you.

**Comment by jbe-dw** [comment]
@mbag Hello, i've been off the pdns project for a while (like a tremendous change of priorities here). Since we rolled back the changes, i'm proposing this patch again.

We stick to your version, so it would be nice to include this one, which i've rebased

Regards

**Comment by jbe-dw** [comment]
Hello here,

It has been a year since I proposed this patch. It is very small. Could you take a look ?

Thank you.

**Comment by networksecadmin** [comment]
Hm… seems like a dead repo. Really pity.

**Comment by mbag** [comment]
@jbe-dw  sorry, this went under my radar. I saw the notification but forgot to take a look. But I must admit, I will have to refresh my memory regarding this repo, so it might take a while.

@networksecadmin  not dead yet, just a little sleepy :grimacing:

**Comment by networksecadmin** [comment]
@mbag I’m happy to hear from you and that this repo isn‘t dead 😄

**Comment by jbe-dw** [comment]
Our setup works fine, we are just bothered that we can't update account into zones. It show a change on each apply even if it said applied. We lack this piece of code to be able to change accounts without doing it manually.

I'm glad to see that you take a look!

**Pull request merged**
