### PR TITLE
feat: Add PowerDNS Zone Account support

### PR DESCRIPTION
**Pull request by jbe-dw**
Hello,

I need to set the "Account" for my zones through Terraform. Here is a bit of code letting the user providing an account. There is no need to create an account separately, it's just a text field. If you prefer I can add a regex check to limit the text format. 

Regards
Elendrys

### CODE REVIEW

**Comment by mbag** [comment]
Hi,
thanks for the Pull request. 

>If you prefer I can add a regex check to limit the text format. 

Yes, this will be needed, because we want to perform input validation before terraform starts applying changes and crashes due to PowerDNS server rejecting our change due to invalid `account` string. However, I was unable to find in documentation what is valid length and character set for `account`. The API documention doesn't mention it https://doc.powerdns.com/authoritative/http-api/zone.html#zone you might need to check definition of SQL schema for that one. Please let me know if you have problem fiding it, I will invest more time in searching it. The PowerDNS documentation isn't good when it comes to http API.

**Comment by jbe-dw** [comment]
I'll look to the database, but it's quite light. I will ask developers in their irc channel, I got a lot of answers there, they are very active (if you need for your developments, you should definitely go there, I've always had an answer within 15 minutes there).

**Comment by jbe-dw** [comment]
The answer is that there's no limitation on this field. Only its length (40). It can accept any UTF-8 character. I'm not sure we should add a regex here

**Comment by mbag** [comment]
Then only length of the input should be tested. Since this attribute has primitive type, you can validate it using https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#validatefunc

Just add that and we should be ready to go.

**Comment by jbe-dw** [comment]
I've already added it and was waiting for your answer.

**Comment by jbe-dw** [comment]
@mbag is it ok now ?

Thank you

**Comment by mbag** [comment]
@jbe-dw  
hi, sorry, I got around to it just now. Code looks OK, I ran tests and `TestAccPDNSZoneAccountEmpty` fails, because of the added check. Is an empty account string allowed for this field? If not, then just convert that test to a negative test, i.e. expect test to fail and add `ExpectError: regexp.MustCompile` (see other negative tests as an example)

**Comment by jbe-dw** [comment]
Yes an empty string is allowed, I can set the lower limit to zero in the validation instead.

**Comment by jbe-dw** [comment]
@mbag I changed the check to match 0 characters as well. The tests failed here with the following error:

```
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
powerdns/resource_powerdns_zone.go:11:2: cannot find package "." in:
	/home/jbe-dw/Documents/Projets/go/jbe-dw_terraform-provider-powerdns/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation
GNUmakefile:15: recipe for target 'test' failed
make: *** [test] Error 1
```
I updated the vendors with `go mod vendor` and add the changes to a separate commit.

**Comment by jbe-dw** [comment]
@mbag up.

Could we manage to get all the patches included within the next days please ?

**Pull request merged**
