### PR TITLE
feat: Add PowerDNS Zone Data

### PR DESCRIPTION
**Pull request by jbe-dw**
Hello,

This PR add a data for pdns zones. It also provides more fields to the resource.

I can surely rebase this branch if you accept my previous PR, there should be no conflict.

Regards

### CODE REVIEW

**Comment by jbe-dw** [comment]
Hello,

This one has been rebased with last merges

Thanks for the feedback

**Comment by jbe-dw** [comment]
Hello,

Can someone review this patch ?

As answered in #70 it allows users to manage their zones with the automatic SOA update successfully.

Thank you

**Comment by mbag** [comment]
Hi, 

I'm skeptical about this  working as described, in case there would be multiple records being updated. Because Zone information (and thus serial) would be retrieved at the beginning and Zone info would have serial from that point in time. But the serial will change on server if other records are added. But this new value wouldn't be retrieved by terraform.
The command would of course succeed, but it would "revert" serial. For this SOA logic to work, the 

You have to keep in mind, that terraform performs resource creation/update/deletion in parallel, and there is no guarantee, the order in which you place resources in tf file, is the order in which they will be created by terraform.

**Comment by jbe-dw** [comment]
The logic is that the data are refreshed before apply. Thus the serial taken from the zone resource is the serial before the changes. It will also match the serial from within the SOA itself, and does not trigger any change on the resource.

The consequence is a stale tfstate as the SOA value not in line at the end of the run. But we don't really care about it as we let PDNS manage it for us. You can force it to run at last with a lot of "depends_on" clauses.

Our use case is to have the zone creation content (zone/soa/ns/mx) in a terraform repository and lets many users manage their own zones in their terraform code. So In fact this is not really an issue. And there is no other way of doing this unless you add a SOA option the powerdns_zone resource and compute it in the code. But you would also have a stale serial because your zone resource must be created first.

Anyway, this patch is just adding output information, and is not about the use I described in the issue. I have run this code with a zone setup then adding or removing other records and it didn't trigger any change on the SOA, which is what anyone letting PowerDNS autoincrement their serial wants.

**Comment by jbe-dw** [comment]
@mbag I'd be glad if the change could be accepted. It is just adding extra properties. 

It doesn't matter if we use these information to suppress the SOA change. PDNS internally updates the serial each time a record is updated. Getting the serial from the zone properties to trick terraform that the desired computed serial exactly matches the actual one (before applying anything on the run) is our use of the property. It has no arm.

It would be nice if we could use the official provider and not our fork

**Pull request closed without merging**
